MIN_FIXES=50                        # Minimum amount of fixes that IGC file must have, not less than 2
MAX_RAWTIME_BETWEEN_FIXES=30.0      # in seconds
MIN_RAWTIME_BETWEEN_FIXES=1.0       # in seconds
MAX_RAWTIME_BETWEEN_FIX_EXCEED=10   # how many fixes can exceed the above limits
MAX_NEW_DAYS_IN_FLIGHT=2            # how many times can a single flight cross UTC 0:00 time
MIN_GSP_FLIGHT=40.0                 # to enter flight mode, km/h
DEG_PER_SEC_MIN_FOR_CIRCLING=4.0    # to enter circing mode, deg/s
MIN_RAWTIME_CIRCLING=60.0           # minimal time to concider circling a thermal
MIN_PRESS_ALT_CHANGE=1e-2           # average absolute change in meters/fix
MIN_GNSS_ALT_CHANGE=1e-2            # average absolute change meters/fix
MAX_PRESS_ALT_CHANGE=50.0           # maximum absolute change, in m/s
MAX_PRESS_ALT_CHANGE_NUM=3          # maximum amount of too much changing fixes per flight
MAX_GNSS_ALT_CHANGE=50.0            # maximum absolute change, in m/s
MAX_GNSS_ALT_CHANGE_NUM=3           # maximum amount of too much changing fixes per flight
MAX_GNSS_ALT=10000                  # maximum absolute altitude
MIN_GNSS_ALT=-600                   # minimum absolute altitude
ALLOWED_GNSS_ALT_VIOLATION_NUM=0    # maximum amount of fixes exceeding the above two limits
MAX_PRESS_ALT=10000                 # maximum absolute altitude
MIN_PRESS_ALT=-600                  # minimum absolute altitude
ALLOWED_PRESS_ALT_VIOLATION_NUM=0   # maximum amount of fixes exceeding the above two limits
MAX_THERMAL_VERTICAL_VEL=7.5        # in m/s
MIN_THERMAL_VERTICAL_VEL=-7.0       # in m/s

EARTH_RADIUS_KM=6371.0
